# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema
trigger:
  branches:
    include:
    - master
    
stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build
    steps:
    - bash: cp -r . $(Build.ArtifactStagingDirectory)
      displayName: create artifact

    - task: PublishBuildArtifacts@1
      displayName: publish artifacts
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: deploy
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: Infrastructure
    - name: environment
      value: 'dev'
    - name: terraform_version
      value: 0.12.24
    - name: terraform_backend_filename
      value: $(environment)-tf-state-file
    - name: resource_group_name
      value: memetrics-$(environment)
    - name: key_vault_name
      value: mm$(environment)-keyvault
  jobs:
    - deployment: deploy
      displayName: Deploy
      pool:
        vmImage: 'Ubuntu-latest'
      # creates an environment if it doesn't exist
      environment: 'dev'
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
            - bash: |
                echo 'environment - $(environment)'
                echo 'Terraform Version - $(terraform_version)'
                echo 'Terraform backend filename - $(terraform_backend_filename)'
              displayName: echo build number

            # https://github.com/MicrosoftDocs/azure-docs/issues/38914
            # Azure Devops is not a trusted Microsoft service and the agents in Azure Devops pool change their IPs weekly
            # This firewall entry is removed at the end of the deployment
            - task: PowerShell@2
              name: GetClientIP
              displayName: Get Agent IP address
              inputs:
                targetType: 'inline'
                script: |
                  $response = Invoke-RestMethod -Uri 'https://api.ipify.org/'
                  Write-Host $response
                  # ##vso setvariable is required to set the value of ipAddr variable. 
                  # $ip_address = $response only works local to the task! ** setvariable must be used to pass the variable down the pipeline.**
                  Write-Host "##vso[task.setvariable variable=ip_address]$response"
                  $ip_address = $response
                  Write-Host ip_address is: $ip_address

            - task: AzureCLI@1
              name: AddFirewallRule
              displayName: Add Firewall Rule to Azure Key Vault
              inputs:
                azureSubscription: 'AzureDevops2022'
                scriptLocation: 'inlineScript'
                inlineScript: 'az keyvault network-rule add --resource-group $(resource_group_name) --name $(key_vault_name) --ip-address $(ip_address)'

            - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
              displayName: 'use terraform $(terraform_version)'
              inputs:
                terraformVersion: $(terraform_version)
            
            - bash: |
                echo '$(AnsibleSecret)' > password
                chmod 600 password
                ansible-vault decrypt $(environment).tfvars --vault-password-file password
              displayName: 'decrypt $(environment).tfvars'
              workingDirectory: '$(System.DefaultWorkingDirectory)/../drop'

            - bash: 'terraform init -backend-config="storage_account_name=$(TerraformStorageAccountName)" -backend-config="container_name=$(TerraformContainerName)" -backend-config="access_key=$(TerraformStorageAccountKey)" -backend-config="key=$(terraform_backend_filename)"'
              displayName: 'terraform init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/../drop'
              env:
                ARM_CLIENT_ID: $(DevopsClientId)
                ARM_TENANT_ID: $(DevopsTenantId)
                ARM_CLIENT_SECRET: $(DevopsClientSecret)
                ARM_SUBSCRIPTION_ID: $(DevopsSubscriptionId)

            - bash: 'terraform workspace select $(environment) || terraform workspace new $(environment)'
              displayName: 'terraform workspace select $(environment)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/../drop'
              env:
                TF_IN_AUTOMATION: 1

            - bash: 'terraform plan -input=false -var-file=$(environment).tfvars -out=$(Build.BuildNumber).tfplan'
              displayName: 'terraform plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/../drop'
              env:
                ARM_CLIENT_ID: $(DevopsClientId)
                ARM_TENANT_ID: $(DevopsTenantId)
                ARM_CLIENT_SECRET: $(DevopsClientSecret)
                ARM_SUBSCRIPTION_ID: $(DevopsSubscriptionId)
                TF_VAR_agent_ip_address: $(ip_address)/32
                TF_WORKSPACE: $(environment)

            - bash: 'terraform apply -input=false $(Build.BuildNumber).tfplan'
              displayName: 'terraform apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/../drop'
              env:
                ARM_CLIENT_ID: $(DevopsClientId)
                ARM_TENANT_ID: $(DevopsTenantId)
                ARM_CLIENT_SECRET: $(DevopsClientSecret)
                ARM_SUBSCRIPTION_ID: $(DevopsSubscriptionId)
                TF_VAR_agent_ip_address: $(ip_address)/32
                TF_WORKSPACE: $(environment)

            - task: AzureCLI@1
              name: RemoveFirewallRule
              displayName: Remove Firewall Rule from Azure Key Vault
              inputs:
                azureSubscription: 'AzureDevops2022'
                scriptLocation: 'inlineScript'
                inlineScript: 'az keyvault network-rule remove --resource-group $(resource_group_name) --name $(key_vault_name) --ip-address $(ip_address)/32'

